---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 281275574-fvqrS1UeN3A3hrv4zPHOxV7Qaj9x5gIiDWTvxYSm
:access_token_secret: izGIrhVdikXX2gjEjVh8ChEwk52d4TNGgDfXMbEyY5eKI
